USE ProductSystem;
GO
CREATE OR ALTER PROCEDURE addProduct(@ID VARCHAR(255),@PNAME VARCHAR(255),@PRICE VARCHAR(255),@CATEGORYID  VARCHAR(255))
AS
BEGIN
    INSERT INTO Products(ID,PNAME,PRICE,CATEGORYID) 
    VALUES(@ID,@PNAME,@PRICE,@CATEGORYID)
   

END;
