USE ProductSystem;
GO
CREATE OR ALTER PROCEDURE updateProduct(@ID VARCHAR(255),@PNAME VARCHAR(255),@PRICE VARCHAR(255),@CATEGORYID  VARCHAR(255))
AS
BEGIN
 UPDATE Products SET ID =@ID, PNAME=@PNAME, PRICE= @PRICE, CATEGORYID= @CATEGORYID WHERE ID = @ID;
END;
